### ISSUE TITLE
Fatal error when executing Pangu

### ISSUE THREAD

**Issue by pbrennan-mvz** [PacificBiosciences/pangu#4]
Hello! 

I am getting a fatal error when executing Pangu. There seems to be a variable 'mult' within the cyp2d6_typer.py script that is being referenced before assignment. Can you recommend a solution to this problem?

This is the output to the terminal:

2024-01-30 11:30:20,342 | DEBUG | Alleles Identified: {'noSV': {'noSV_0': ('*2', '*34', '*39'), 'noSV_1': ('*39',)}, 'duplicate': {'duplicate_0': ('*41', '*2', '*34', '*39', '*119')}}
2024-01-30 11:30:20,343 | INFO | Calling Diplotype
2024-01-30 11:30:20,343 | WARNING | Multi-tandem DUP call -- check reads
2024-01-30 11:30:20,343 | ERROR | No DUP parent found for tandem *41
2024-01-30 11:30:20,525 | DEBUG | Alleles Identified: {'noSV': {'noSV_0': ('*3',), 'noSV_1': ('*4', '*10', '*39', '*74')}}
2024-01-30 11:30:20,526 | INFO | Calling Diplotype
2024-01-30 11:30:20,526 | INFO | Diplotype called: CYP2D6 *3/*4
2024-01-30 11:30:20,527 | DEBUG | Alleles Identified: {'noSV': {'noSV_0': ('*1',), 'noSV_1': ('*39',)}, 'duplicate': {'duplicate_0': ('*2', '*34', '*39')}}
2024-01-30 11:30:20,527 | INFO | Calling Diplotype
2024-01-30 11:30:20,527 | WARNING | Multi-tandem DUP call -- check reads
2024-01-30 11:30:20,527 | ERROR | No DUP parent found for tandem *2

Here is the python error:
Traceback (most recent call last):
  File "/mnt/stg_wgs/scripts/PGx_pipeline/.snakemake/conda/016965f96f004ecaf59532db2b753d93/bin/pangu", line 10, in <module>
    sys.exit(main_cli())
  File "/mnt/stg_wgs/scripts/PGx_pipeline/.snakemake/conda/016965f96f004ecaf59532db2b753d93/lib/python3.10/site-packages/pangu/__main__.py", line 122, in main_cli
    starTyper = main( parser )
  File "/mnt/stg_wgs/scripts/PGx_pipeline/.snakemake/conda/016965f96f004ecaf59532db2b753d93/lib/python3.10/site-packages/pangu/__main__.py", line 61, in main
    typer.run( bamfile, vcffile )
  File "/mnt/stg_wgs/scripts/PGx_pipeline/.snakemake/conda/016965f96f004ecaf59532db2b753d93/lib/python3.10/site-packages/pangu/cyp2d6_typer.py", line 78, in run
    self.diplotype._make_diplotype()
  File "/mnt/stg_wgs/scripts/PGx_pipeline/.snakemake/conda/016965f96f004ecaf59532db2b753d93/lib/python3.10/site-packages/pangu/cyp2d6_typer.py", line 510, in _make_diplotype
    self.haplotypes.append( ( f'{allele}x{dcount}', calls.pop(allele), mult ) )
UnboundLocalError: local variable 'mult' referenced before assignment

**Comment by pbrennan-mvz** [comment]
I actually have another error with a different sample. Here is that one:

Traceback (most recent call last):
  File "/mnt/stg_wgs/scripts/PGx_pipeline/.snakemake/conda/016965f96f004ecaf59532db2b753d93/bin/pangu", line 10, in <module>
    sys.exit(main_cli())
  File "/mnt/stg_wgs/scripts/PGx_pipeline/.snakemake/conda/016965f96f004ecaf59532db2b753d93/lib/python3.10/site-packages/pangu/__main__.py", line 122, in main_cli
    starTyper = main( parser )
  File "/mnt/stg_wgs/scripts/PGx_pipeline/.snakemake/conda/016965f96f004ecaf59532db2b753d93/lib/python3.10/site-packages/pangu/__main__.py", line 61, in main
    typer.run( bamfile, vcffile )
  File "/mnt/stg_wgs/scripts/PGx_pipeline/.snakemake/conda/016965f96f004ecaf59532db2b753d93/lib/python3.10/site-packages/pangu/cyp2d6_typer.py", line 78, in run
    self.diplotype._make_diplotype()
  File "/mnt/stg_wgs/scripts/PGx_pipeline/.snakemake/conda/016965f96f004ecaf59532db2b753d93/lib/python3.10/site-packages/pangu/cyp2d6_typer.py", line 474, in _make_diplotype
    nosv, dups, dels = [ Counter( [ calls[0] for calls in self.calls.get( atype, {} ).values() ] )
  File "/mnt/stg_wgs/scripts/PGx_pipeline/.snakemake/conda/016965f96f004ecaf59532db2b753d93/lib/python3.10/site-packages/pangu/cyp2d6_typer.py", line 474, in <listcomp>
    nosv, dups, dels = [ Counter( [ calls[0] for calls in self.calls.get( atype, {} ).values() ] )
  File "/mnt/stg_wgs/scripts/PGx_pipeline/.snakemake/conda/016965f96f004ecaf59532db2b753d93/lib/python3.10/site-packages/pangu/cyp2d6_typer.py", line 474, in <listcomp>
    nosv, dups, dels = [ Counter( [ calls[0] for calls in self.calls.get( atype, {} ).values() ] )
IndexError: tuple index out of range

**Comment by pbrennan-mvz** [comment]
Hi! Sorry for getting back to your late. For the "out of range" error, I see this as the Pangu output:

2024-02-05 10:32:58,790 | INFO | Processing /srv/nfs/ngsdata/Projects/Tender_Pharmacogenetics/dragen_data_internal_samples/results/pacbio/50151577.M13_bc1004_F--M13_bc1055_R.pbaa_passed_cluster_sequences.bam
2024-02-05 10:33:00,337 | INFO | Identifying SV signatures
2024-02-05 10:33:00,502 | INFO | Phasing and Calling Alleles
2024-02-05 10:33:00,503 | DEBUG | Calling noSV
2024-02-05 10:33:00,504 | DEBUG | Attempting to phase noSV reads
2024-02-05 10:33:00,504 | DEBUG | Reseting HP for 7 noSV  reads
2024-02-05 10:33:00,711 | DEBUG | Positions used for read clustering: [42123210, 42123218, 42123225, 42123235, 42123236, 42123237, 42123238, 42123242, 42123243, 42123251, 42123253, 42123299, 42123307, 42123310, 42123311, 42123538, 42123630, 42123642, 42123651, 42124105, 42124797, 42125571, 42125619, 42125923, 42125979, 42126068, 42126131, 42126309, 42126389, 42126610, 42126913, 42127000, 42127206, 42127208, 42127355, 42127406, 42127607, 42127940, 42128498, 42128575, 42128667, 42128693, 42128944, 42129129, 42129131, 42129179, 42129753, 42129795, 42129808, 42129818, 42129949, 42130046, 42130481, 42130546, 42130558, 42130559, 42130564, 42130568, 42130570, 42130577, 42130691, 42130966, 42131468, 42131530, 42131790, 42132198, 42132208, 42132216, 42132374, 42132384, 42132560]
2024-02-05 10:33:07,406 | DEBUG | Alleles Identified: {'noSV': {'noSV_0': (), 'noSV_1': ('*2', '*34', '*39')}}
2024-02-05 10:33:07,406 | INFO | Calling Diplotype

**Comment by pbrennan-mvz** [comment]
Hi John! Was there any update on this? Was the Pangu output I provided helpful?

**Comment by jrharting** [comment]
Hi!  Yes, thakn you for the extra info -- this was indeed enough to identify and fix the problem.  The latest version (0.2.4) should work -- let me know if you have any other issues!

**Comment by jrharting** [comment]
fixed in 0.2.4

**Comment by pbrennan-mvz** [comment]
Hi! I pulled the new version, and it fixed some of my samples, but I am still having an issue on one. Can you take a look at these error messages?

2024-02-26 12:34:42,494 | INFO | Processing /srv/nfs/ngsdata/Projects/Tender_Pharmacogenetics/internal_samples_illumina_comparison/dragen_data_internal_samples/results/pacbio/50151589.M13_bc1009_F--M13_bc1050_R.pbaa_passed_cluster_sequences.bam
2024-02-26 12:34:44,373 | INFO | Identifying SV signatures
2024-02-26 12:34:44,568 | INFO | Phasing and Calling Alleles
2024-02-26 12:34:44,569 | DEBUG | Calling noSV
2024-02-26 12:34:44,570 | DEBUG | Attempting to phase noSV reads
2024-02-26 12:34:44,571 | DEBUG | Reseting HP for 4 noSV  reads
2024-02-26 12:34:44,791 | DEBUG | Positions used for read clustering: [42123210, 42123218, 42123225, 42123235, 42123236, 42123237, 42123238, 42123242, 42123243, 42123251, 42123253, 42123299, 42123307, 42123310, 42123311, 42123538, 42123630, 42124105, 42124797, 42125923, 42125979, 42126068, 42126131, 42126309, 42126389, 42126610, 42127000, 42127206, 42127208, 42127406, 42127940, 42128693, 42128944, 42129129, 42129795, 42129808, 42129818, 42129949, 42130046, 42130481, 42130546, 42130558, 42130559, 42130564, 42130568, 42130570, 42130577, 42130691, 42131468, 42131530, 42131790, 42132216, 42132374, 42132560]
2024-02-26 12:34:54,819 | DEBUG | Calling duplicate
2024-02-26 12:34:59,707 | DEBUG | Alleles Identified: {'noSV': {'noSV_0': ('*4', '*10', '*39', '*74'), 'noSV_1': ('*4', '*10', '*65', '*2', '*34', '*39', '*74')}, 'duplicate': {'duplicate_0': ('*2', '*34', '*39')}}
2024-02-26 12:34:59,707 | INFO | Calling Diplotype
2024-02-26 12:34:59,707 | WARNING | Multi-tandem DUP call -- check reads
2024-02-26 12:34:59,707 | ERROR | No DUP parent found for tandem *2
Traceback (most recent call last):
  File "/mnt/stg_wgs/scripts/PGx_pipeline/.snakemake/scripts/tmplftx9ucy.wrapper.py", line 16, in <module>
    shell(
  File "/home/pbrennan/miniconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/shell.py", line 287, in __new__
    raise sp.CalledProcessError(retcode, cmd)


Here is the error:

Traceback (most recent call last):
  File "/mnt/stg_wgs/scripts/PGx_pipeline/.snakemake/conda/3b24d641831797150e212867dfcbde2a/bin/pangu", line 10, in <module>
    sys.exit(main_cli())
  File "/mnt/stg_wgs/scripts/PGx_pipeline/.snakemake/conda/3b24d641831797150e212867dfcbde2a/lib/python3.10/site-packages/pangu/__main__.py", line 126, in main_cli
    starTyper = main( parser )
  File "/mnt/stg_wgs/scripts/PGx_pipeline/.snakemake/conda/3b24d641831797150e212867dfcbde2a/lib/python3.10/site-packages/pangu/__main__.py", line 65, in main
    typer.run( bamfile, vcffile )
  File "/mnt/stg_wgs/scripts/PGx_pipeline/.snakemake/conda/3b24d641831797150e212867dfcbde2a/lib/python3.10/site-packages/pangu/cyp2d6_typer.py", line 78, in run
    self.diplotype._make_diplotype()
  File "/mnt/stg_wgs/scripts/PGx_pipeline/.snakemake/conda/3b24d641831797150e212867dfcbde2a/lib/python3.10/site-packages/pangu/cyp2d6_typer.py", line 516, in _make_diplotype
    self.haplotypes.append( ( f'{allele}x{dcount}', calls.pop(allele), mult ) )
UnboundLocalError: local variable 'mult' referenced before assignment

**Comment by pbrennan-mvz** [comment]
Hi! Just checking in --  was there any update on this?

**Comment by jrharting** [comment]
apologies!  I've been slammed recently -- I'll take a look and get back to you as soon as i can!

**Comment by jrharting** [comment]
hi again, sorry for the long delay.  I just published an update that should fix that bug.  Please give it a try and let me know.

**Comment by jrharting** [comment]
sorry for the hassle -- after I published the last result, something looked off and it turned out I created a bug with the fix to the last one.  These should all be fixed in v0.2.6 (just published).  thank yoo for your patience!!

**Comment by pbrennan-mvz** [comment]
Thanks John! Do you know when 2.6.0 will be available through conda?

**Comment by jrharting** [comment]
i am guessing soon --  the bot has picked up the update https://github.com/bioconda/bioconda-recipes/pull/46752#event-12243649180, but it might still be updating mirrors??  not sure what the time delay is exactly.

if you really want to try it right away, you can also clone the repo and then `pip install .` from the cloned repo :)

**Comment by pbrennan-mvz** [comment]
Hi John! I was able to pull the version 2.6.0 from conda, but unfortunatly I am still getting an error.

2024-04-02 14:23:17,377 | INFO | Processing results/internal_pgx_samples_all_variants_forcegt_test_only/pacbio/50151589.M13_bc1009_F--M13_bc1050_R.pbaa_passed_cluster_sequences.bam
2024-04-02 14:23:18,514 | INFO | Identifying SV signatures
2024-04-02 14:23:18,635 | INFO | Phasing and Calling Alleles
2024-04-02 14:23:18,636 | DEBUG | Calling noSV
2024-04-02 14:23:18,637 | DEBUG | Attempting to phase noSV reads
2024-04-02 14:23:18,637 | DEBUG | Reseting HP for 4 noSV  reads
2024-04-02 14:23:18,775 | DEBUG | Positions used for read clustering: [42123210, 42123218, 42123225, 42123235, 42123236, 42123237, 42123238, 42123242, 42123243, 42123251, 42123253, 42123299, 42123307, 42123310, 42123311, 42123538, 42123630, 42124105, 42124797, 42125923, 42125979, 42126068, 42126131, 42126309, 42126389, 42126610, 42127000, 42127206, 42127208, 42127406, 42127940, 42128693, 42128944, 42129129, 42129795, 42129808, 42129818, 42129949, 42130046, 42130481, 42130546, 42130558, 42130559, 42130564, 42130568, 42130570, 42130577, 42130691, 42131468, 42131530, 42131790, 42132216, 42132374, 42132560]
2024-04-02 14:23:24,268 | DEBUG | Calling duplicate
2024-04-02 14:23:26,881 | DEBUG | Alleles Identified: {'noSV': {'noSV_0': ('*4', '*10', '*39', '*74'), 'noSV_1': ('*4', '*10', '*65', '*2', '*34', '*39', '*74')}, 'duplicate': {'duplicate_0': ('*2', '*34', '*39')}}
2024-04-02 14:23:26,881 | INFO | Calling Diplotype
2024-04-02 14:23:26,882 | WARNING | Multi-tandem DUP call -- check reads
2024-04-02 14:23:26,882 | ERROR | No DUP parent found for tandem *2
2024-04-02 14:23:26,882 | ERROR | Extra haplotypes called: [('*2x1', ['duplicate_0'], 1), ('*4', ['noSV_0']), ('*4', ['noSV_1'])]
Traceback (most recent call last):
  File "/mnt/stg_wgs/scripts/PGx_pipeline/.snakemake/conda/383bc07cbc5f0b8fea6f90a69550b588/bin/pangu", line 10, in <module>
    sys.exit(main_cli())
  File "/mnt/stg_wgs/scripts/PGx_pipeline/.snakemake/conda/383bc07cbc5f0b8fea6f90a69550b588/lib/python3.10/site-packages/pangu/__main__.py", line 127, in main_cli
    starTyper = main( parser )
  File "/mnt/stg_wgs/scripts/PGx_pipeline/.snakemake/conda/383bc07cbc5f0b8fea6f90a69550b588/lib/python3.10/site-packages/pangu/__main__.py", line 65, in main
    typer.run( bamfile, vcffile )
  File "/mnt/stg_wgs/scripts/PGx_pipeline/.snakemake/conda/383bc07cbc5f0b8fea6f90a69550b588/lib/python3.10/site-packages/pangu/cyp2d6_typer.py", line 78, in run
    self.diplotype._make_diplotype()
  File "/mnt/stg_wgs/scripts/PGx_pipeline/.snakemake/conda/383bc07cbc5f0b8fea6f90a69550b588/lib/python3.10/site-packages/pangu/cyp2d6_typer.py", line 572, in _make_diplotype
    self.diplotype = self.joinHaplotypes( self.haplotypes )
  File "/mnt/stg_wgs/scripts/PGx_pipeline/.snakemake/conda/383bc07cbc5f0b8fea6f90a69550b588/lib/python3.10/site-packages/pangu/cyp2d6_typer.py", line 589, in joinHaplotypes
    return '/'.join( h if type( h ) == str else h[0]
  File "/mnt/stg_wgs/scripts/PGx_pipeline/.snakemake/conda/383bc07cbc5f0b8fea6f90a69550b588/lib/python3.10/site-packages/pangu/cyp2d6_typer.py", line 590, in <genexpr>
    for h,lbls in haps )
ValueError: too many values to unpack (expected 2)

Could you take another look at this? Thanks!

**Comment by jrharting** [comment]
yike, i'm so sorry you keep hitting these bugs!  it looks like this is a bit of an edge case where a parent tandem dup is not identified, and i had a typo in the conditional.  Its fixed in the `bug_fix` branch -- are you able to clone the bug_fix branch and `pip install .` to test it quick?  else i can just merge it in, but i'd rather avoid any more bugs before releasing a new version, if possible!   thanks!

**Comment by pbrennan-mvz** [comment]
Hi John! I just did a test, and the fix worked :)

**Comment by jrharting** [comment]
thanks for checking!  i've merged the latest as v0.2.7.  It mightntake a couple days again for bioconda to auto-update the image.
